[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 1

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "daze"
directory = "~/.config/leftwm/themes/daze"
version = "1.0.0"
leftwm_versions = "*"
current = true
