scratchpad_space = 8
launch_timeout = 5

[[scratchpad]]
name = "telegram"
target_type = "app"
target = "Telegram"
position = [0, 1]
size = [2, 6]
rows = 8
cols = 8
launch_type = "app"
launch_command = "Telegram.app"

[[scratchpad]]
name = "alacritty"
target_type = "title"
target = "AlacrittyScratchpad"
position = [1, 1]
size = [6, 6]
rows = 8
cols = 8
launch_type = "app_with_arg"
launch_command = ["Alacritty.app", "--title", "AlacrittyScratchpad"]

[[scratchpad]]
name = "discord"
target_type = "app"
target = "Vesktop"
position = [1, 1]
size = [6, 6]
rows = 8
cols = 8
launch_type = "app"
launch_command = "Vesktop.app"
