#!/usr/bin/env bash

if [[ -z $1 ]]; then
    options=("zsh" "tmux" "bash" "fish" "alacritty" "neovim" "installscript" "vifm" "xinitrc" "rofi" "picom" "leftwm" "shkd" "theme" "scripts" "conf")
    selected_option=$(printf '%s\n' "${options[@]}" | fzf)
    if [[ -z $selected_option ]]; then
        exit 0
    fi
else
    selected_option=$1
fi

case $selected_option in
    "zsh" | "z")
        command nvim ~/.zshrc && source ~/.zshrc
        ;;
    "tmux" | "mux")
        command nvim ~/.config/tmux/tmux.conf
        ;;
    "bash")
        command nvim ~/.bashrc
        ;;
    "fish")
        pwd=$(pwd)
        cd ~/.config/fish && nvim ~/.config/fish/config.fish && cd $pwd
        ;;
    "alacritty" | "ala")
        command nvim ~/.config/alacritty/alacritty.toml
        ;;
    "vim" | "vi" | "nvim" | "neovim")
        pwd=$(pwd)
        cd ~/.config/nvim && nvim ~/.config/nvim/init.lua && cd $pwd
        ;;
    "ins" | "installscript")
        command nvim ~/.config/script/install.sh
        ;;
    "fm" | "vifm")
        command nvim ~/.config/vifm/vifmrc
        ;;
    "x" | "xinit" | "xinitrc")
        command nvim ~/.xinitrc
        ;;
    "r" | "rofi")
        command nvim ~/.config/rofi
        ;;
    "p" | "picom")
        command nvim ~/.config/picom.conf
        ;;
    "leftwm" | "wm")
        command nvim ~/.config/leftwm/config.ron
        ;;
    "shkd" | "binds" | "sxhkd" | "skhd")
        command nvim ~/.config/skhd/skhdrc
        ;;
    "script" | "scripts")
        command nvim ~/.local/scripts/
        ;;
    "conf")
        command nvim ~/.local/scripts/conf
        ;;
    "wmtheme" | "theme")
        pwd=$(pwd)
        cd ~/.config/leftwm && nvim ~/.config/leftwm/themes.toml && cd $pwd
        ;;
    *)
        echo "Invalid option: $selected_option"
        exit 1
        ;;
esac

