#!/usr/bin/env bash

if [[ $1 == "zsh" || $1 == "z" ]]; then
    command nvim ~/.zshrc && source ~/.zshrc
fi
if [[ $1 == "tmux" || $1 == "mux" ]]; then
    command nvim ~/.tmux.conf
fi
if [[ $1 == "bash" ]]; then
    command nvim ~/.bashrc
fi
if [[ $1 == "fish" ]]; then
    pwd=$(pwd)
    cd ~/.config/fish && nvim ~/.config/fish/config.fish && cd $pwd
fi
if [[ $1 == "alacritty" || $1 == "ala" ]]; then
    command nvim ~/.config/alacritty/alacritty.yml
fi
if [[ $1 == "vim" || $1 == "vi" || $1 == "nvim" ]]; then
    pwd=$(pwd)
    cd ~/.config/nvim && nvim ~/.config/nvim/init.lua && cd $pwd
fi
if [[ $1 == "ins" || $1 == "installscript" ]]; then
    command nvim ~/.config/script/install.sh
fi
if [[ $1 == "fm" || $1 == "vifm" ]]; then
    command nvim ~/.config/vifm/vifmrc
fi
if [[ $1 == "x" || $1 == "xinit" ]]; then
    command nvim ~/.xinitrc
fi
if [[ $1 == "r" || $1 == "rofi" ]]; then
    command nvim ~/.config/rofi
fi
if [[ $1 == "p" || $1 == "picom" ]]; then
    command nvim ~/.config/picom.conf
fi
if [[ $1 == "leftwm" || $1 == "wm" ]]; then
    command nvim ~/.config/leftwm/config.toml
fi
if [[ $1 == "shkd" || $1 == "binds" || $1 == "sxhkd" || $1 == "skhd" ]]; then
    command nvim ~/.config/skhd/skhdrc
fi
if [[ $1 == "wmtheme" || $1 == "theme" ]]; then
    pwd=$(pwd)
    cd ~/.config/leftwm && nvim ~/.config/leftwm/themes.toml && cd $pwd
fi

