#!/bin/bash


# Define variables
CONTAINER_NAME="global_postgres"
POSTGRES_PASSWORD="postgres"
POSTGRES_DB="postgres"
HOST_PORT=5432


# Check if the container already exists
if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
  # Container already exists, start it if it's not running
  if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
    echo "PostgreSQL container '$CONTAINER_NAME' is already running and accessible on port $HOST_PORT."
  else
    docker start $CONTAINER_NAME > /dev/null
    echo "PostgreSQL container '$CONTAINER_NAME' was already created. Starting it now."
    echo "PostgreSQL container '$CONTAINER_NAME' is running and accessible on port $HOST_PORT."
  fi
else
  # Container does not exist, create and run it
  docker run -d \
    --name $CONTAINER_NAME \
    -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    -e POSTGRES_DB=$POSTGRES_DB \
    -p $HOST_PORT:5432 \
    supabase/postgres:15.8.1.035_amd64 > /dev/null


  # Check if the container was successfully created and started
  if [ $? -eq 0 ]; then
    echo "PostgreSQL container '$CONTAINER_NAME' is running and accessible on port $HOST_PORT."
  else
    echo "Failed to start PostgreSQL container."
  fi
fi
 
