#!/bin/bash

# Define variables
CONTAINER_NAME="global_mysql"
MYSQL_ROOT_PASSWORD="root"
MYSQL_DATABASE="lis"
HOST_PORT=3306

# Check if the container already exists
if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
  # Container already exists, start it if it's not running
  if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
    echo "MySQL container '$CONTAINER_NAME' is already running and accessible on port $HOST_PORT."
  else
    docker start $CONTAINER_NAME > /dev/null
    echo "MySQL container '$CONTAINER_NAME' was already created. Starting it now."
    echo "MySQL container '$CONTAINER_NAME' is running and accessible on port $HOST_PORT."
  fi
else
  # Container does not exist, create and run it
  docker run -d \
    --name $CONTAINER_NAME \
    -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
    -e MYSQL_DATABASE=$MYSQL_DATABASE \
    -p $HOST_PORT:3306 \
    mysql:latest > /dev/null

  # Check if the container was successfully created and started
  if [ $? -eq 0 ]; then
    echo "MySQL container '$CONTAINER_NAME' is running and accessible on port $HOST_PORT."
  else
    echo "Failed to start MySQL container."
  fi
fi

