#!/usr/bin/env -S bash -e

if [[ $1 == "install" ]]; then
    command sudo pacman -S ${@:2}
fi
if [[ $1 == "remove" ]]; then
    appname=${@:2}

    if [ -z "$2" ]; then
      appname=$(pacman -Q | fzf | awk '{print $1;}')
    fi

    command sudo pacman -Rns $appname
fi
if [[ $1 == "uninstall" ]]; then
    command sudo pacman -Rns ${@:2}
fi
if [[ $1 == "update" ]]; then
    command sudo pacman -Syu
    command yay -Syu
fi
if [[ $1 == "list" ]]; then
    command pacman -Q
fi
