#!/usr/bin/env bash

SCREENLAYOUT_DIR="$HOME/.screenlayout"

if [[ -z $1 ]]; then
    options=($(ls "$SCREENLAYOUT_DIR"/*.sh | xargs -n1 basename | sed 's/\.sh$//'))
    selected_option=$(printf '%s\n' "${options[@]}" | fzf --prompt="Select monitor configuration: ")
    if [[ -z $selected_option ]]; then
        exit 0
    fi
else
    selected_option=$1
fi

script_path="$SCREENLAYOUT_DIR/${selected_option}.sh"

if [[ -f "$script_path" ]]; then
    bash "$script_path"
    leftwm-command SoftReload
else
    echo "Invalid option or script not found: $selected_option"
    exit 1
fi
