#!/bin/bash

# Get the content of the clipboard
content=$(xclip -o -selection clipboard)

sleep 0.5
# Type out each character individually using xdotool
for (( i=0; i<${#content}; i++ )); do
    xdotool type --delay 50 "${content:$i:1}"
done
