#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents/Projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux has-session -t $selected_name > /dev/null 2>&1 
if [ $? ]
then
  command tmux new-session -d -s $selected_name -c $selected > /dev/null 2>&1
fi

tmux attach -t $selected_name
