[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1a1e25"
foreground = '#7f85a3'

[colors.cursor]
text   = '#7f85a3'
cursor = '#FFFFFF'

[colors.normal]
black   = '#444a73'
red     = '#ff5370'
green   = '#4fd6be'
yellow  = '#ffc777'
blue    = '#3e68d7'
magenta = '#fc7b7b'
cyan    = '#86e1fc'
white   = '#d1d0d0'

[colors.bright]
black   = '#828bb8'
red     = '#ff98a4'
green   = '#c3e88d'
yellow  = '#ffc777'
blue    = '#82aaff'
magenta = '#ff966c'
cyan    = '#b4f9f8'
white   = '#5f8787'

[colors.selection]
background = "0xbbc2cf"
text = "0x1c1f24"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.bold]
family = "iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 5000

[window]
decorations = "none"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
